import type { Problem } from "./types";

// Generated from merged_problems.json for the Patterns practice links.
export const generatedPatternProblems: Problem[] = [
  {
    id: "lc-3",
    source: "leetcode",
    number: 3,
    title: "Longest Substring Without Repeating Characters",
    slug: "longest-substring-without-repeating-characters",
    difficulty: "Medium",
    topics: ["Hash Table", "String", "Sliding Window"],
    descriptionMarkdown:
      "# 3. Longest Substring Without Repeating Characters\n\nGiven a string s, find the length of the longest substring without duplicate characters.\nExample 1:\nExample 2:\nExample 3:\nConstraints:\n\n## Constraints\n\n- 0 <= s.length <= 5 * 104\n- s consists of English letters, digits, symbols and spaces.\n\n## Hints\n\n- Generate all possible substrings & check for each substring if it's valid and keep updating maxLen accordingly.",
    notesMarkdown: "",
    functionName: "lengthOfLongestSubstring",
    judgeMode: "exact",
    code: "/**\n * @param {string} s\n * @return {number}\n */\nvar lengthOfLongestSubstring = function(s) {\n    \n};",
    testCases: [
      {
        id: "lc-3-case-1",
        input: 's = "abcabcbb"',
        expected: "3",
      },
      {
        id: "lc-3-case-2",
        input: 's = "bbbbb"',
        expected: "1",
      },
      {
        id: "lc-3-case-3",
        input: 's = "pwwkew"',
        expected: "3",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-11",
    source: "leetcode",
    number: 11,
    title: "Container With Most Water",
    slug: "container-with-most-water",
    difficulty: "Medium",
    topics: ["Array", "Two Pointers", "Greedy"],
    descriptionMarkdown:
      "# 11. Container With Most Water\n\nYou are given an integer array height of length n. There are n vertical lines drawn such that the two endpoints of the ith line are (i, 0) and (i, height[i]).\nFind two lines that together with the x-axis form a container, such that the container contains the most water.\nReturn the maximum amount of water a container can store.\nNotice that you may not slant the container.\nExample 1:\nExample 2:\nConstraints:\n\n## Constraints\n\n- n == height.length\n- 2 <= n <= 105\n- 0 <= height[i] <= 104\n\n## Hints\n\n- If you simulate the problem, it will be O(n^2) which is not efficient.\n- Try to use two-pointers. Set one pointer to the left and one to the right of the array. Always move the pointer that points to the lower line.\n- How can you calculate the amount of water at each step?",
    notesMarkdown: "",
    functionName: "maxArea",
    judgeMode: "exact",
    code: "/**\n * @param {number[]} height\n * @return {number}\n */\nvar maxArea = function(height) {\n    \n};",
    testCases: [
      {
        id: "lc-11-case-1",
        input: "height = [1,8,6,2,5,4,8,3,7]",
        expected: "49",
      },
      {
        id: "lc-11-case-2",
        input: "height = [1,1]",
        expected: "1",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-15",
    source: "leetcode",
    number: 15,
    title: "3Sum",
    slug: "3sum",
    difficulty: "Medium",
    topics: ["Array", "Two Pointers", "Sorting"],
    descriptionMarkdown:
      "# 15. 3Sum\n\nGiven an integer array nums, return all the triplets [nums[i], nums[j], nums[k]] such that i != j, i != k, and j != k, and nums[i] + nums[j] + nums[k] == 0.\nNotice that the solution set must not contain duplicate triplets.\nExample 1:\nExample 2:\nExample 3:\nConstraints:\n\n## Constraints\n\n- 3 <= nums.length <= 3000\n- -105 <= nums[i] <= 105\n\n## Hints\n\n- So, we essentially need to find three numbers x, y, and z such that they add up to the given value. If we fix one of the numbers say x, we are left with the two-sum problem at hand!\n- For the two-sum problem, if we fix one of the numbers, say x, we have to scan the entire array to find the next number y, which is value - x where value is the input parameter. Can we change our array somehow so that this search becomes faster?\n- The second train of thought for two-sum is, without changing the array, can we use additional space somehow? Like maybe a hash map to speed up the search?",
    notesMarkdown: "",
    functionName: "threeSum",
    judgeMode: "exact",
    code: "/**\n * @param {number[]} nums\n * @return {number[][]}\n */\nvar threeSum = function(nums) {\n    \n};",
    testCases: [
      {
        id: "lc-15-case-1",
        input: "nums = [-1,0,1,2,-1,-4]",
        expected: "[[-1,-1,2],[-1,0,1]]",
      },
      {
        id: "lc-15-case-2",
        input: "nums = [0,1,1]",
        expected: "[]",
      },
      {
        id: "lc-15-case-3",
        input: "nums = [0,0,0]",
        expected: "[[0,0,0]]",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-23",
    source: "leetcode",
    number: 23,
    title: "Merge k Sorted Lists",
    slug: "merge-k-sorted-lists",
    difficulty: "Hard",
    topics: ["Linked List", "Divide and Conquer", "Heap (Priority Queue)", "Merge Sort"],
    descriptionMarkdown:
      "# 23. Merge k Sorted Lists\n\nYou are given an array of k linked-lists lists, each linked-list is sorted in ascending order.\nMerge all the linked-lists into one sorted linked-list and return it.\nExample 1:\nExample 2:\nExample 3:\nConstraints:\n\n## Constraints\n\n- k == lists.length\n- 0 <= k <= 104\n- 0 <= lists[i].length <= 500\n- -104 <= lists[i][j] <= 104\n- lists[i] is sorted in ascending order.\n- The sum of lists[i].length will not exceed 104.",
    notesMarkdown: "",
    functionName: "mergeKLists",
    judgeMode: "exact",
    code: "/**\n * Definition for singly-linked list.\n * function ListNode(val, next) {\n *     this.val = (val===undefined ? 0 : val)\n *     this.next = (next===undefined ? null : next)\n * }\n */\n/**\n * @param {ListNode[]} lists\n * @return {ListNode}\n */\nvar mergeKLists = function(lists) {\n    \n};",
    testCases: [
      {
        id: "lc-23-case-1",
        input: "lists = [[1,4,5],[1,3,4],[2,6]]",
        expected: "[1,1,2,3,4,4,5,6]",
      },
      {
        id: "lc-23-case-2",
        input: "lists = []",
        expected: "[]",
      },
      {
        id: "lc-23-case-3",
        input: "lists = [[]]",
        expected: "[]",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-24",
    source: "leetcode",
    number: 24,
    title: "Swap Nodes in Pairs",
    slug: "swap-nodes-in-pairs",
    difficulty: "Medium",
    topics: ["Linked List", "Recursion"],
    descriptionMarkdown:
      "# 24. Swap Nodes in Pairs\n\nGiven a linked list, swap every two adjacent nodes and return its head. You must solve the problem without modifying the values in the list's nodes (i.e., only nodes themselves may be changed.)\nExample 1:\nExample 2:\nExample 3:\nExample 4:\nConstraints:\n\n## Constraints\n\n- The number of nodes in the list is in the range [0, 100].\n- 0 <= Node.val <= 100",
    notesMarkdown: "",
    functionName: "swapPairs",
    judgeMode: "exact",
    code: "/**\n * Definition for singly-linked list.\n * function ListNode(val, next) {\n *     this.val = (val===undefined ? 0 : val)\n *     this.next = (next===undefined ? null : next)\n * }\n */\n/**\n * @param {ListNode} head\n * @return {ListNode}\n */\nvar swapPairs = function(head) {\n    \n};",
    testCases: [
      {
        id: "lc-24-case-1",
        input: "head = [1,2,3,4]",
        expected: "[2,1,4,3]",
      },
      {
        id: "lc-24-case-2",
        input: "head = []",
        expected: "[]",
      },
      {
        id: "lc-24-case-3",
        input: "head = [1]",
        expected: "[1]",
      },
      {
        id: "lc-24-case-4",
        input: "head = [1,2,3]",
        expected: "[2,1,3]",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-25",
    source: "leetcode",
    number: 25,
    title: "Reverse Nodes in k-Group",
    slug: "reverse-nodes-in-k-group",
    difficulty: "Hard",
    topics: ["Linked List", "Recursion"],
    descriptionMarkdown:
      "# 25. Reverse Nodes in k-Group\n\nGiven the head of a linked list, reverse the nodes of the list k at a time, and return the modified list.\nk is a positive integer and is less than or equal to the length of the linked list. If the number of nodes is not a multiple of k then left-out nodes, in the end, should remain as it is.\nYou may not alter the values in the list's nodes, only nodes themselves may be changed.\nExample 1:\nExample 2:\nConstraints:\nFollow-up: Can you solve the problem in O(1) extra memory space?\n\n## Constraints\n\n- The number of nodes in the list is n.\n- 1 <= k <= n <= 5000\n- 0 <= Node.val <= 1000",
    notesMarkdown: "",
    functionName: "reverseKGroup",
    judgeMode: "exact",
    code: "/**\n * Definition for singly-linked list.\n * function ListNode(val, next) {\n *     this.val = (val===undefined ? 0 : val)\n *     this.next = (next===undefined ? null : next)\n * }\n */\n/**\n * @param {ListNode} head\n * @param {number} k\n * @return {ListNode}\n */\nvar reverseKGroup = function(head, k) {\n    \n};",
    testCases: [
      {
        id: "lc-25-case-1",
        input: "head = [1,2,3,4,5], k = 2",
        expected: "[2,1,4,3,5]",
      },
      {
        id: "lc-25-case-2",
        input: "head = [1,2,3,4,5], k = 3",
        expected: "[3,2,1,4,5]",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-33",
    source: "leetcode",
    number: 33,
    title: "Search in Rotated Sorted Array",
    slug: "search-in-rotated-sorted-array",
    difficulty: "Medium",
    topics: ["Array", "Binary Search"],
    descriptionMarkdown:
      "# 33. Search in Rotated Sorted Array\n\nThere is an integer array nums sorted in ascending order (with distinct values).\nPrior to being passed to your function, nums is possibly rotated at an unknown pivot index k (1 <= k < nums.length) such that the resulting array is [nums[k], nums[k+1], ..., nums[n-1], nums[0], nums[1], ..., nums[k-1]] (0-indexed). For example, [0,1,2,4,5,6,7] might be rotated at pivot index 3 and become [4,5,6,7,0,1,2].\nGiven the array nums after the possible rotation and an integer target, return the index of target if it is in nums, or -1 if it is not in nums.\nYou must write an algorithm with O(log n) runtime complexity.\nExample 1:\nExample 2:\nExample 3:\nConstraints:\n\n## Constraints\n\n- 1 <= nums.length <= 5000\n- -104 <= nums[i] <= 104\n- All values of nums are unique.\n- nums is an ascending array that is possibly rotated.\n- -104 <= target <= 104",
    notesMarkdown: "",
    functionName: "search",
    judgeMode: "exact",
    code: "/**\n * @param {number[]} nums\n * @param {number} target\n * @return {number}\n */\nvar search = function(nums, target) {\n    \n};",
    testCases: [
      {
        id: "lc-33-case-1",
        input: "nums = [4,5,6,7,0,1,2], target = 0",
        expected: "4",
      },
      {
        id: "lc-33-case-2",
        input: "nums = [4,5,6,7,0,1,2], target = 3",
        expected: "-1",
      },
      {
        id: "lc-33-case-3",
        input: "nums = [1], target = 0",
        expected: "-1",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-34",
    source: "leetcode",
    number: 34,
    title: "Find First and Last Position of Element in Sorted Array",
    slug: "find-first-and-last-position-of-element-in-sorted-array",
    difficulty: "Medium",
    topics: ["Array", "Binary Search"],
    descriptionMarkdown:
      "# 34. Find First and Last Position of Element in Sorted Array\n\nGiven an array of integers nums sorted in non-decreasing order, find the starting and ending position of a given target value.\nIf target is not found in the array, return [-1, -1].\nYou must write an algorithm with O(log n) runtime complexity.\nExample 1:\nExample 2:\nExample 3:\nConstraints:\n\n## Constraints\n\n- 0 <= nums.length <= 105\n- -109 <= nums[i] <= 109\n- nums is a non-decreasing array.\n- -109 <= target <= 109",
    notesMarkdown: "",
    functionName: "searchRange",
    judgeMode: "exact",
    code: "/**\n * @param {number[]} nums\n * @param {number} target\n * @return {number[]}\n */\nvar searchRange = function(nums, target) {\n    \n};",
    testCases: [
      {
        id: "lc-34-case-1",
        input: "nums = [5,7,7,8,8,10], target = 8",
        expected: "[3,4]",
      },
      {
        id: "lc-34-case-2",
        input: "nums = [5,7,7,8,8,10], target = 6",
        expected: "[-1,-1]",
      },
      {
        id: "lc-34-case-3",
        input: "nums = [], target = 0",
        expected: "[-1,-1]",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-46",
    source: "leetcode",
    number: 46,
    title: "Permutations",
    slug: "permutations",
    difficulty: "Medium",
    topics: ["Array", "Backtracking"],
    descriptionMarkdown:
      "# 46. Permutations\n\nGiven an array nums of distinct integers, return all the possible permutations. You can return the answer in any order.\nExample 1:\nExample 2:\nExample 3:\nConstraints:\n\n## Constraints\n\n- 1 <= nums.length <= 6\n- -10 <= nums[i] <= 10\n- All the integers of nums are unique.",
    notesMarkdown: "",
    functionName: "permute",
    judgeMode: "unordered-array",
    code: "/**\n * @param {number[]} nums\n * @return {number[][]}\n */\nvar permute = function(nums) {\n    \n};",
    testCases: [
      {
        id: "lc-46-case-1",
        input: "nums = [1,2,3]",
        expected: "[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]",
      },
      {
        id: "lc-46-case-2",
        input: "nums = [0,1]",
        expected: "[[0,1],[1,0]]",
      },
      {
        id: "lc-46-case-3",
        input: "nums = [1]",
        expected: "[[1]]",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-51",
    source: "leetcode",
    number: 51,
    title: "N-Queens",
    slug: "n-queens",
    difficulty: "Hard",
    topics: ["Array", "Backtracking"],
    descriptionMarkdown:
      "# 51. N-Queens\n\nThe n-queens puzzle is the problem of placing n queens on an n x n chessboard such that no two queens attack each other.\nGiven an integer n, return all distinct solutions to the n-queens puzzle. You may return the answer in any order.\nEach solution contains a distinct board configuration of the n-queens' placement, where 'Q' and '.' both indicate a queen and an empty space, respectively.\nExample 1:\nExample 2:\nConstraints:\n\n## Constraints\n\n- 1 <= n <= 9",
    notesMarkdown: "",
    functionName: "solveNQueens",
    judgeMode: "unordered-array",
    code: "/**\n * @param {number} n\n * @return {string[][]}\n */\nvar solveNQueens = function(n) {\n    \n};",
    testCases: [
      {
        id: "lc-51-case-1",
        input: "n = 4",
        expected: '[[".Q..","...Q","Q...","..Q."],["..Q.","Q...","...Q",".Q.."]]',
      },
      {
        id: "lc-51-case-2",
        input: "n = 1",
        expected: '[["Q"]]',
      },
    ],
    submissions: [],
  },
  {
    id: "lc-56",
    source: "leetcode",
    number: 56,
    title: "Merge Intervals",
    slug: "merge-intervals",
    difficulty: "Medium",
    topics: ["Array", "Sorting"],
    descriptionMarkdown:
      "# 56. Merge Intervals\n\nGiven an array of intervals where intervals[i] = [starti, endi], merge all overlapping intervals, and return an array of the non-overlapping intervals that cover all the intervals in the input.\nExample 1:\nExample 2:\nConstraints:\n\n## Constraints\n\n- 1 <= intervals.length <= 104\n- intervals[i].length == 2\n- 0 <= starti <= endi <= 104",
    notesMarkdown: "",
    functionName: "merge",
    judgeMode: "exact",
    code: "/**\n * @param {number[][]} intervals\n * @return {number[][]}\n */\nvar merge = function(intervals) {\n    \n};",
    testCases: [
      {
        id: "lc-56-case-1",
        input: "intervals = [[1,3],[2,6],[8,10],[15,18]]",
        expected: "[[1,6],[8,10],[15,18]]",
      },
      {
        id: "lc-56-case-2",
        input: "intervals = [[1,4],[4,5]]",
        expected: "[[1,5]]",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-57",
    source: "leetcode",
    number: 57,
    title: "Insert Interval",
    slug: "insert-interval",
    difficulty: "Medium",
    topics: ["Array"],
    descriptionMarkdown:
      "# 57. Insert Interval\n\nYou are given an array of non-overlapping intervals intervals where intervals[i] = [starti, endi] represent the start and the end of the ith interval and intervals is sorted in ascending order by starti. You are also given an interval newInterval = [start, end] that represents the start and end of another interval.\nInsert newInterval into intervals such that intervals is still sorted in ascending order by starti and intervals still does not have any overlapping intervals (merge overlapping intervals if necessary).\nReturn intervals after the insertion.\nNote that you don't need to modify intervals in-place. You can make a new array and return it.\nExample 1:\nExample 2:\nConstraints:\n\n## Constraints\n\n- 0 <= intervals.length <= 104\n- intervals[i].length == 2\n- 0 <= starti <= endi <= 105\n- intervals is sorted by starti in ascending order.\n- newInterval.length == 2\n- 0 <= start <= end <= 105\n\n## Hints\n\n- Intervals Array is sorted. Can you use Binary Search to find the correct position to insert the new Interval.?\n- Can you try merging the overlapping intervals while inserting the new interval?\n- This can be done by comparing the end of the last interval with the start of the new interval and vice versa.",
    notesMarkdown: "",
    functionName: "insert",
    judgeMode: "exact",
    code: "/**\n * @param {number[][]} intervals\n * @param {number[]} newInterval\n * @return {number[][]}\n */\nvar insert = function(intervals, newInterval) {\n    \n};",
    testCases: [
      {
        id: "lc-57-case-1",
        input: "intervals = [[1,3],[6,9]], newInterval = [2,5]",
        expected: "[[1,5],[6,9]]",
      },
      {
        id: "lc-57-case-2",
        input: "intervals = [[1,2],[3,5],[6,7],[8,10],[12,16]], newInterval = [4,8]",
        expected: "[[1,2],[3,10],[12,16]]",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-70",
    source: "leetcode",
    number: 70,
    title: "Climbing Stairs",
    slug: "climbing-stairs",
    difficulty: "Easy",
    topics: ["Math", "Dynamic Programming", "Memoization"],
    descriptionMarkdown:
      "# 70. Climbing Stairs\n\nYou are climbing a staircase. It takes n steps to reach the top.\nEach time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?\nExample 1:\nExample 2:\nConstraints:\n\n## Constraints\n\n- 1 <= n <= 45\n\n## Hints\n\n- To reach nth step, what could have been your previous steps? (Think about the step sizes)",
    notesMarkdown: "",
    functionName: "climbStairs",
    judgeMode: "exact",
    code: "/**\n * @param {number} n\n * @return {number}\n */\nvar climbStairs = function(n) {\n    \n};",
    testCases: [
      {
        id: "lc-70-case-1",
        input: "n = 2",
        expected: "2",
      },
      {
        id: "lc-70-case-2",
        input: "n = 3",
        expected: "3",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-76",
    source: "leetcode",
    number: 76,
    title: "Minimum Window Substring",
    slug: "minimum-window-substring",
    difficulty: "Hard",
    topics: ["Hash Table", "String", "Sliding Window"],
    descriptionMarkdown:
      '# 76. Minimum Window Substring\n\nGiven two strings s and t of lengths m and n respectively, return the minimum window substring of s such that every character in t (including duplicates) is included in the window. If there is no such substring, return the empty string "".\nThe testcases will be generated such that the answer is unique.\nExample 1:\nExample 2:\nExample 3:\nConstraints:\nFollow up: Could you find an algorithm that runs in O(m + n) time?\n\n## Constraints\n\n- m == s.length\n- n == t.length\n- 1 <= m, n <= 105\n- s and t consist of uppercase and lowercase English letters.\n\n## Hints\n\n- Use two pointers to create a window of letters in s, which would have all the characters from t.\n- Expand the right pointer until all the characters of t are covered.\n- Once all the characters are covered, move the left pointer and ensure that all the characters are still covered to minimize the subarray size.\n- Continue expanding the right and left pointers until you reach the end of s.',
    notesMarkdown: "",
    functionName: "minWindow",
    judgeMode: "exact",
    code: "/**\n * @param {string} s\n * @param {string} t\n * @return {string}\n */\nvar minWindow = function(s, t) {\n    \n};",
    testCases: [
      {
        id: "lc-76-case-1",
        input: 's = "ADOBECODEBANC", t = "ABC"',
        expected: '"BANC"',
      },
      {
        id: "lc-76-case-2",
        input: 's = "a", t = "a"',
        expected: '"a"',
      },
      {
        id: "lc-76-case-3",
        input: 's = "a", t = "aa"',
        expected: '""',
      },
    ],
    submissions: [],
  },
  {
    id: "lc-78",
    source: "leetcode",
    number: 78,
    title: "Subsets",
    slug: "subsets",
    difficulty: "Medium",
    topics: ["Array", "Backtracking", "Bit Manipulation"],
    descriptionMarkdown:
      "# 78. Subsets\n\nGiven an integer array nums of unique elements, return all possible subsets (the power set).\nThe solution set must not contain duplicate subsets. Return the solution in any order.\nExample 1:\nExample 2:\nConstraints:\n\n## Constraints\n\n- 1 <= nums.length <= 10\n- -10 <= nums[i] <= 10\n- All the numbers of nums are unique.",
    notesMarkdown: "",
    functionName: "subsets",
    judgeMode: "unordered-array",
    code: "/**\n * @param {number[]} nums\n * @return {number[][]}\n */\nvar subsets = function(nums) {\n    \n};",
    testCases: [
      {
        id: "lc-78-case-1",
        input: "nums = [1,2,3]",
        expected: "[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]",
      },
      {
        id: "lc-78-case-2",
        input: "nums = [0]",
        expected: "[[],[0]]",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-84",
    source: "leetcode",
    number: 84,
    title: "Largest Rectangle in Histogram",
    slug: "largest-rectangle-in-histogram",
    difficulty: "Hard",
    topics: ["Array", "Stack", "Monotonic Stack"],
    descriptionMarkdown:
      "# 84. Largest Rectangle in Histogram\n\nGiven an array of integers heights representing the histogram's bar height where the width of each bar is 1, return the area of the largest rectangle in the histogram.\nExample 1:\nExample 2:\nConstraints:\n\n## Constraints\n\n- 1 <= heights.length <= 105\n- 0 <= heights[i] <= 104",
    notesMarkdown: "",
    functionName: "largestRectangleArea",
    judgeMode: "exact",
    code: "/**\n * @param {number[]} heights\n * @return {number}\n */\nvar largestRectangleArea = function(heights) {\n    \n};",
    testCases: [
      {
        id: "lc-84-case-1",
        input: "heights = [2,1,5,6,2,3]",
        expected: "10",
      },
      {
        id: "lc-84-case-2",
        input: "heights = [2,4]",
        expected: "4",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-92",
    source: "leetcode",
    number: 92,
    title: "Reverse Linked List II",
    slug: "reverse-linked-list-ii",
    difficulty: "Medium",
    topics: ["Linked List"],
    descriptionMarkdown:
      "# 92. Reverse Linked List II\n\nGiven the head of a singly linked list and two integers left and right where left <= right, reverse the nodes of the list from position left to position right, and return the reversed list.\nExample 1:\nExample 2:\nConstraints:\n\n## Constraints\n\n- The number of nodes in the list is n.\n- 1 <= n <= 500\n- -500 <= Node.val <= 500\n- 1 <= left <= right <= n",
    notesMarkdown: "",
    functionName: "reverseBetween",
    judgeMode: "exact",
    code: "/**\n * Definition for singly-linked list.\n * function ListNode(val, next) {\n *     this.val = (val===undefined ? 0 : val)\n *     this.next = (next===undefined ? null : next)\n * }\n */\n/**\n * @param {ListNode} head\n * @param {number} left\n * @param {number} right\n * @return {ListNode}\n */\nvar reverseBetween = function(head, left, right) {\n    \n};",
    testCases: [
      {
        id: "lc-92-case-1",
        input: "head = [1,2,3,4,5], left = 2, right = 4",
        expected: "[1,4,3,2,5]",
      },
      {
        id: "lc-92-case-2",
        input: "head = [5], left = 1, right = 1",
        expected: "[5]",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-102",
    source: "leetcode",
    number: 102,
    title: "Binary Tree Level Order Traversal",
    slug: "binary-tree-level-order-traversal",
    difficulty: "Medium",
    topics: ["Tree", "Breadth-First Search", "Binary Tree"],
    descriptionMarkdown:
      "# 102. Binary Tree Level Order Traversal\n\nGiven the root of a binary tree, return the level order traversal of its nodes' values. (i.e., from left to right, level by level).\nExample 1:\nExample 2:\nExample 3:\nConstraints:\n\n## Constraints\n\n- The number of nodes in the tree is in the range [0, 2000].\n- -1000 <= Node.val <= 1000\n\n## Hints\n\n- Use a queue to perform BFS.",
    notesMarkdown: "",
    functionName: "levelOrder",
    judgeMode: "exact",
    code: "/**\n * Definition for a binary tree node.\n * function TreeNode(val, left, right) {\n *     this.val = (val===undefined ? 0 : val)\n *     this.left = (left===undefined ? null : left)\n *     this.right = (right===undefined ? null : right)\n * }\n */\n/**\n * @param {TreeNode} root\n * @return {number[][]}\n */\nvar levelOrder = function(root) {\n    \n};",
    testCases: [
      {
        id: "lc-102-case-1",
        input: "root = [3,9,20,null,null,15,7]",
        expected: "[[3],[9,20],[15,7]]",
      },
      {
        id: "lc-102-case-2",
        input: "root = [1]",
        expected: "[[1]]",
      },
      {
        id: "lc-102-case-3",
        input: "root = []",
        expected: "[]",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-104",
    source: "leetcode",
    number: 104,
    title: "Maximum Depth of Binary Tree",
    slug: "maximum-depth-of-binary-tree",
    difficulty: "Easy",
    topics: ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
    descriptionMarkdown:
      "# 104. Maximum Depth of Binary Tree\n\nGiven the root of a binary tree, return its maximum depth.\nA binary tree's maximum depth is the number of nodes along the longest path from the root node down to the farthest leaf node.\nExample 1:\nExample 2:\nConstraints:\n\n## Constraints\n\n- The number of nodes in the tree is in the range [0, 104].\n- -100 <= Node.val <= 100",
    notesMarkdown: "",
    functionName: "maxDepth",
    judgeMode: "exact",
    code: "/**\n * Definition for a binary tree node.\n * function TreeNode(val, left, right) {\n *     this.val = (val===undefined ? 0 : val)\n *     this.left = (left===undefined ? null : left)\n *     this.right = (right===undefined ? null : right)\n * }\n */\n/**\n * @param {TreeNode} root\n * @return {number}\n */\nvar maxDepth = function(root) {\n    \n};",
    testCases: [
      {
        id: "lc-104-case-1",
        input: "root = [3,9,20,null,null,15,7]",
        expected: "3",
      },
      {
        id: "lc-104-case-2",
        input: "root = [1,null,2]",
        expected: "2",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-105",
    source: "leetcode",
    number: 105,
    title: "Construct Binary Tree from Preorder and Inorder Traversal",
    slug: "construct-binary-tree-from-preorder-and-inorder-traversal",
    difficulty: "Medium",
    topics: ["Array", "Hash Table", "Divide and Conquer", "Tree", "Binary Tree"],
    descriptionMarkdown:
      "# 105. Construct Binary Tree from Preorder and Inorder Traversal\n\nGiven two integer arrays preorder and inorder where preorder is the preorder traversal of a binary tree and inorder is the inorder traversal of the same tree, construct and return the binary tree.\nExample 1:\nExample 2:\nConstraints:\n\n## Constraints\n\n- 1 <= preorder.length <= 3000\n- inorder.length == preorder.length\n- -3000 <= preorder[i], inorder[i] <= 3000\n- preorder and inorder consist of unique values.\n- Each value of inorder also appears in preorder.\n- preorder is guaranteed to be the preorder traversal of the tree.\n- inorder is guaranteed to be the inorder traversal of the tree.",
    notesMarkdown: "",
    functionName: "buildTree",
    judgeMode: "exact",
    code: "/**\n * Definition for a binary tree node.\n * function TreeNode(val, left, right) {\n *     this.val = (val===undefined ? 0 : val)\n *     this.left = (left===undefined ? null : left)\n *     this.right = (right===undefined ? null : right)\n * }\n */\n/**\n * @param {number[]} preorder\n * @param {number[]} inorder\n * @return {TreeNode}\n */\nvar buildTree = function(preorder, inorder) {\n    \n};",
    testCases: [
      {
        id: "lc-105-case-1",
        input: "preorder = [3,9,20,15,7], inorder = [9,3,15,20,7]",
        expected: "[3,9,20,null,null,15,7]",
      },
      {
        id: "lc-105-case-2",
        input: "preorder = [-1], inorder = [-1]",
        expected: "[-1]",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-113",
    source: "leetcode",
    number: 113,
    title: "Path Sum II",
    slug: "path-sum-ii",
    difficulty: "Medium",
    topics: ["Backtracking", "Tree", "Depth-First Search", "Binary Tree"],
    descriptionMarkdown:
      "# 113. Path Sum II\n\nGiven the root of a binary tree and an integer targetSum, return all root-to-leaf paths where the sum of the node values in the path equals targetSum. Each path should be returned as a list of the node values, not node references.\nA root-to-leaf path is a path starting from the root and ending at any leaf node. A leaf is a node with no children.\nExample 1:\nExample 2:\nExample 3:\nConstraints:\n\n## Constraints\n\n- The number of nodes in the tree is in the range [0, 5000].\n- -1000 <= Node.val <= 1000\n- -1000 <= targetSum <= 1000",
    notesMarkdown: "",
    functionName: "pathSum",
    judgeMode: "exact",
    code: "/**\n * Definition for a binary tree node.\n * function TreeNode(val, left, right) {\n *     this.val = (val===undefined ? 0 : val)\n *     this.left = (left===undefined ? null : left)\n *     this.right = (right===undefined ? null : right)\n * }\n */\n/**\n * @param {TreeNode} root\n * @param {number} targetSum\n * @return {number[][]}\n */\nvar pathSum = function(root, targetSum) {\n    \n};",
    testCases: [
      {
        id: "lc-113-case-1",
        input: "root = [5,4,8,11,null,13,4,7,2,null,null,5,1], targetSum = 22",
        expected: "[[5,4,11,2],[5,8,4,5]]",
      },
      {
        id: "lc-113-case-2",
        input: "root = [1,2,3], targetSum = 5",
        expected: "[]",
      },
      {
        id: "lc-113-case-3",
        input: "root = [1,2], targetSum = 0",
        expected: "[]",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-124",
    source: "leetcode",
    number: 124,
    title: "Binary Tree Maximum Path Sum",
    slug: "binary-tree-maximum-path-sum",
    difficulty: "Hard",
    topics: ["Dynamic Programming", "Tree", "Depth-First Search", "Binary Tree"],
    descriptionMarkdown:
      "# 124. Binary Tree Maximum Path Sum\n\nA path in a binary tree is a sequence of nodes where each pair of adjacent nodes in the sequence has an edge connecting them. A node can only appear in the sequence at most once. Note that the path does not need to pass through the root.\nThe path sum of a path is the sum of the node's values in the path.\nGiven the root of a binary tree, return the maximum path sum of any non-empty path.\nExample 1:\nExample 2:\nConstraints:\n\n## Constraints\n\n- The number of nodes in the tree is in the range [1, 3 * 104].\n- -1000 <= Node.val <= 1000",
    notesMarkdown: "",
    functionName: "maxPathSum",
    judgeMode: "exact",
    code: "/**\n * Definition for a binary tree node.\n * function TreeNode(val, left, right) {\n *     this.val = (val===undefined ? 0 : val)\n *     this.left = (left===undefined ? null : left)\n *     this.right = (right===undefined ? null : right)\n * }\n */\n/**\n * @param {TreeNode} root\n * @return {number}\n */\nvar maxPathSum = function(root) {\n    \n};",
    testCases: [
      {
        id: "lc-124-case-1",
        input: "root = [1,2,3]",
        expected: "6",
      },
      {
        id: "lc-124-case-2",
        input: "root = [-10,9,20,null,null,15,7]",
        expected: "42",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-125",
    source: "leetcode",
    number: 125,
    title: "Valid Palindrome",
    slug: "valid-palindrome",
    difficulty: "Easy",
    topics: ["Two Pointers", "String"],
    descriptionMarkdown:
      "# 125. Valid Palindrome\n\nA phrase is a palindrome if, after converting all uppercase letters into lowercase letters and removing all non-alphanumeric characters, it reads the same forward and backward. Alphanumeric characters include letters and numbers.\nGiven a string s, return true if it is a palindrome, or false otherwise.\nExample 1:\nExample 2:\nExample 3:\nConstraints:\n\n## Constraints\n\n- 1 <= s.length <= 2 * 105\n- s consists only of printable ASCII characters.",
    notesMarkdown: "",
    functionName: "isPalindrome",
    judgeMode: "exact",
    code: "/**\n * @param {string} s\n * @return {boolean}\n */\nvar isPalindrome = function(s) {\n    \n};",
    testCases: [
      {
        id: "lc-125-case-1",
        input: 's = "A man, a plan, a canal: Panama"',
        expected: "true",
      },
      {
        id: "lc-125-case-2",
        input: 's = "race a car"',
        expected: "false",
      },
      {
        id: "lc-125-case-3",
        input: 's = " "',
        expected: "true",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-127",
    source: "leetcode",
    number: 127,
    title: "Word Ladder",
    slug: "word-ladder",
    difficulty: "Hard",
    topics: ["Hash Table", "String", "Breadth-First Search"],
    descriptionMarkdown:
      "# 127. Word Ladder\n\nA transformation sequence from word beginWord to word endWord using a dictionary wordList is a sequence of words beginWord -> s1 -> s2 -> ... -> sk such that:\nGiven two words, beginWord and endWord, and a dictionary wordList, return the number of words in the shortest transformation sequence from beginWord to endWord, or 0 if no such sequence exists.\nExample 1:\nExample 2:\nConstraints:\n\n## Constraints\n\n- 1 <= beginWord.length <= 10\n- endWord.length == beginWord.length\n- 1 <= wordList.length <= 5000\n- wordList[i].length == beginWord.length\n- beginWord, endWord, and wordList[i] consist of lowercase English letters.\n- beginWord != endWord\n- All the words in wordList are unique.",
    notesMarkdown: "",
    functionName: "ladderLength",
    judgeMode: "exact",
    code: "/**\n * @param {string} beginWord\n * @param {string} endWord\n * @param {string[]} wordList\n * @return {number}\n */\nvar ladderLength = function(beginWord, endWord, wordList) {\n    \n};",
    testCases: [
      {
        id: "lc-127-case-1",
        input:
          'beginWord = "hit", endWord = "cog", wordList = ["hot","dot","dog","lot","log","cog"]',
        expected: "5",
      },
      {
        id: "lc-127-case-2",
        input: 'beginWord = "hit", endWord = "cog", wordList = ["hot","dot","dog","lot","log"]',
        expected: "0",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-130",
    source: "leetcode",
    number: 130,
    title: "Surrounded Regions",
    slug: "surrounded-regions",
    difficulty: "Medium",
    topics: ["Array", "Depth-First Search", "Breadth-First Search", "Union Find", "Matrix"],
    descriptionMarkdown:
      "# 130. Surrounded Regions\n\nYou are given an m x n matrix board containing letters 'X' and 'O', capture regions that are surrounded:\nTo capture a surrounded region, replace all 'O's with 'X's in-place within the original board. You do not need to return anything.\nExample 1:\nExample 2:\nConstraints:\n\n## Constraints\n\n- m == board.length\n- n == board[i].length\n- 1 <= m, n <= 200\n- board[i][j] is 'X' or 'O'.",
    notesMarkdown: "",
    functionName: "solve",
    judgeMode: "exact",
    code: "/**\n * @param {character[][]} board\n * @return {void} Do not return anything, modify board in-place instead.\n */\nvar solve = function(board) {\n    \n};",
    testCases: [
      {
        id: "lc-130-case-1",
        input: 'board = [["X","X","X","X"],["X","O","O","X"],["X","X","O","X"],["X","O","X","X"]]',
        expected: '[["X","X","X","X"],["X","X","X","X"],["X","X","X","X"],["X","O","X","X"]]',
      },
      {
        id: "lc-130-case-2",
        input: 'board = [["X"]]',
        expected: '[["X"]]',
      },
    ],
    submissions: [],
  },
  {
    id: "lc-133",
    source: "leetcode",
    number: 133,
    title: "Clone Graph",
    slug: "clone-graph",
    difficulty: "Medium",
    topics: ["Hash Table", "Depth-First Search", "Breadth-First Search", "Graph"],
    descriptionMarkdown:
      "# 133. Clone Graph\n\nGiven a reference of a node in a connected undirected graph.\nReturn a deep copy (clone) of the graph.\nEach node in the graph contains a value (int) and a list (List[Node]) of its neighbors.\nTest case format:\nFor simplicity, each node's value is the same as the node's index (1-indexed). For example, the first node with val == 1, the second node with val == 2, and so on. The graph is represented in the test case using an adjacency list.\nAn adjacency list is a collection of unordered lists used to represent a finite graph. Each list describes the set of neighbors of a node in the graph.\nThe given node will always be the first node with val = 1. You must return the copy of the given node as a reference to the cloned graph.\nExample 1:\nExample 2:\nExample 3:\nConstraints:\n\n## Constraints\n\n- The number of nodes in the graph is in the range [0, 100].\n- 1 <= Node.val <= 100\n- Node.val is unique for each node.\n- There are no repeated edges and no self-loops in the graph.\n- The Graph is connected and all nodes can be visited starting from the given node.",
    notesMarkdown: "",
    functionName: "cloneGraph",
    judgeMode: "exact",
    code: "/**\n * // Definition for a _Node.\n * function _Node(val, neighbors) {\n *    this.val = val === undefined ? 0 : val;\n *    this.neighbors = neighbors === undefined ? [] : neighbors;\n * };\n */\n\n/**\n * @param {_Node} node\n * @return {_Node}\n */\nvar cloneGraph = function(node) {\n    \n};",
    testCases: [
      {
        id: "lc-133-case-2",
        input: "adjList = [[2,4],[1,3],[2,4],[1,3]]",
        expected: "[[2,4],[1,3],[2,4],[1,3]]",
      },
      {
        id: "lc-133-case-3",
        input: "adjList = [[]]",
        expected: "[[]]",
      },
      {
        id: "lc-133-case-4",
        input: "adjList = []",
        expected: "[]",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-136",
    source: "leetcode",
    number: 136,
    title: "Single Number",
    slug: "single-number",
    difficulty: "Easy",
    topics: ["Array", "Bit Manipulation"],
    descriptionMarkdown:
      "# 136. Single Number\n\nGiven a non-empty array of integers nums, every element appears twice except for one. Find that single one.\nYou must implement a solution with a linear runtime complexity and use only constant extra space.\nExample 1:\nExample 2:\nExample 3:\nConstraints:\n\n## Constraints\n\n- 1 <= nums.length <= 3 * 104\n- -3 * 104 <= nums[i] <= 3 * 104\n- Each element in the array appears twice except for one element which appears only once.\n\n## Hints\n\n- Think about the XOR (^) operator's property.",
    notesMarkdown: "",
    functionName: "singleNumber",
    judgeMode: "exact",
    code: "/**\n * @param {number[]} nums\n * @return {number}\n */\nvar singleNumber = function(nums) {\n    \n};",
    testCases: [
      {
        id: "lc-136-case-1",
        input: "nums = [2,2,1]",
        expected: "1",
      },
      {
        id: "lc-136-case-2",
        input: "nums = [4,1,2,1,2]",
        expected: "4",
      },
      {
        id: "lc-136-case-3",
        input: "nums = [1]",
        expected: "1",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-141",
    source: "leetcode",
    number: 141,
    title: "Linked List Cycle",
    slug: "linked-list-cycle",
    difficulty: "Easy",
    topics: ["Hash Table", "Linked List", "Two Pointers"],
    descriptionMarkdown:
      "# 141. Linked List Cycle\n\nGiven head, the head of a linked list, determine if the linked list has a cycle in it.\nThere is a cycle in a linked list if there is some node in the list that can be reached again by continuously following the next pointer. Internally, pos is used to denote the index of the node that tail's next pointer is connected to. Note that pos is not passed as a parameter.\nReturn true if there is a cycle in the linked list. Otherwise, return false.\nExample 1:\nExample 2:\nExample 3:\nConstraints:\nFollow up: Can you solve it using O(1) (i.e. constant) memory?\n\n## Constraints\n\n- The number of the nodes in the list is in the range [0, 104].\n- -105 <= Node.val <= 105\n- pos is -1 or a valid index in the linked-list.",
    notesMarkdown: "",
    functionName: "hasCycle",
    judgeMode: "exact",
    code: "/**\n * Definition for singly-linked list.\n * function ListNode(val) {\n *     this.val = val;\n *     this.next = null;\n * }\n */\n\n/**\n * @param {ListNode} head\n * @return {boolean}\n */\nvar hasCycle = function(head) {\n    \n};",
    testCases: [
      {
        id: "lc-141-case-1",
        input: "head = [3,2,0,-4], pos = 1",
        expected: "true",
      },
      {
        id: "lc-141-case-2",
        input: "head = [1,2], pos = 0",
        expected: "true",
      },
      {
        id: "lc-141-case-3",
        input: "head = [1], pos = -1",
        expected: "false",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-142",
    source: "leetcode",
    number: 142,
    title: "Linked List Cycle II",
    slug: "linked-list-cycle-ii",
    difficulty: "Medium",
    topics: ["Hash Table", "Linked List", "Two Pointers"],
    descriptionMarkdown:
      "# 142. Linked List Cycle II\n\nGiven the head of a linked list, return the node where the cycle begins. If there is no cycle, return null.\nThere is a cycle in a linked list if there is some node in the list that can be reached again by continuously following the next pointer. Internally, pos is used to denote the index of the node that tail's next pointer is connected to (0-indexed). It is -1 if there is no cycle. Note that pos is not passed as a parameter.\nDo not modify the linked list.\nExample 1:\nExample 2:\nExample 3:\nConstraints:\nFollow up: Can you solve it using O(1) (i.e. constant) memory?\n\n## Constraints\n\n- The number of the nodes in the list is in the range [0, 104].\n- -105 <= Node.val <= 105\n- pos is -1 or a valid index in the linked-list.",
    notesMarkdown: "",
    functionName: "detectCycle",
    judgeMode: "exact",
    code: "/**\n * Definition for singly-linked list.\n * function ListNode(val) {\n *     this.val = val;\n *     this.next = null;\n * }\n */\n\n/**\n * @param {ListNode} head\n * @return {ListNode}\n */\nvar detectCycle = function(head) {\n    \n};",
    testCases: [
      {
        id: "lc-142-case-1",
        input: "head = [3,2,0,-4], pos = 1",
        expected: "tail connects to node index 1",
      },
      {
        id: "lc-142-case-2",
        input: "head = [1,2], pos = 0",
        expected: "tail connects to node index 0",
      },
      {
        id: "lc-142-case-3",
        input: "head = [1], pos = -1",
        expected: "no cycle",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-153",
    source: "leetcode",
    number: 153,
    title: "Find Minimum in Rotated Sorted Array",
    slug: "find-minimum-in-rotated-sorted-array",
    difficulty: "Medium",
    topics: ["Array", "Binary Search"],
    descriptionMarkdown:
      "# 153. Find Minimum in Rotated Sorted Array\n\nSuppose an array of length n sorted in ascending order is rotated between 1 and n times. For example, the array nums = [0,1,2,4,5,6,7] might become:\nNotice that rotating an array [a[0], a[1], a[2], ..., a[n-1]] 1 time results in the array [a[n-1], a[0], a[1], a[2], ..., a[n-2]].\nGiven the sorted rotated array nums of unique elements, return the minimum element of this array.\nYou must write an algorithm that runs in O(log n) time.\nExample 1:\nExample 2:\nExample 3:\nConstraints:\n\n## Constraints\n\n- n == nums.length\n- 1 <= n <= 5000\n- -5000 <= nums[i] <= 5000\n- All the integers of nums are unique.\n- nums is sorted and rotated between 1 and n times.\n\n## Hints\n\n- Array was originally in ascending order. Now that the array is rotated, there would be a point in the array where there is a small deflection from the increasing sequence. eg. The array would be something like [4, 5, 6, 7, 0, 1, 2].\n- You can divide the search space into two and see which direction to go.\r\nCan you think of an algorithm which has O(logN) search complexity?\n- <ol>\r\n<li>All the elements to the left of inflection point > first element of the array.</li>\r\n<li>All the elements to the right of inflection point < first element of the array.</li>\r\n<ol>",
    notesMarkdown: "",
    functionName: "findMin",
    judgeMode: "exact",
    code: "/**\n * @param {number[]} nums\n * @return {number}\n */\nvar findMin = function(nums) {\n    \n};",
    testCases: [
      {
        id: "lc-153-case-1",
        input: "nums = [3,4,5,1,2]",
        expected: "1",
      },
      {
        id: "lc-153-case-2",
        input: "nums = [4,5,6,7,0,1,2]",
        expected: "0",
      },
      {
        id: "lc-153-case-3",
        input: "nums = [11,13,15,17]",
        expected: "11",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-167",
    source: "leetcode",
    number: 167,
    title: "Two Sum II - Input Array Is Sorted",
    slug: "two-sum-ii-input-array-is-sorted",
    difficulty: "Medium",
    topics: ["Array", "Two Pointers", "Binary Search"],
    descriptionMarkdown:
      "# 167. Two Sum II - Input Array Is Sorted\n\nGiven a 1-indexed array of integers numbers that is already sorted in non-decreasing order, find two numbers such that they add up to a specific target number. Let these two numbers be numbers[index1] and numbers[index2] where 1 <= index1 < index2 <= numbers.length.\nReturn the indices of the two numbers, index1 and index2, added by one as an integer array [index1, index2] of length 2.\nThe tests are generated such that there is exactly one solution. You may not use the same element twice.\nYour solution must use only constant extra space.\nExample 1:\nExample 2:\nExample 3:\nConstraints:\n\n## Constraints\n\n- 2 <= numbers.length <= 3 * 104\n- -1000 <= numbers[i] <= 1000\n- numbers is sorted in non-decreasing order.\n- -1000 <= target <= 1000\n- The tests are generated such that there is exactly one solution.",
    notesMarkdown: "",
    functionName: "twoSum",
    judgeMode: "exact",
    code: "/**\n * @param {number[]} numbers\n * @param {number} target\n * @return {number[]}\n */\nvar twoSum = function(numbers, target) {\n    \n};",
    testCases: [
      {
        id: "lc-167-case-1",
        input: "numbers = [2,7,11,15], target = 9",
        expected: "[1,2]",
      },
      {
        id: "lc-167-case-2",
        input: "numbers = [2,3,4], target = 6",
        expected: "[1,3]",
      },
      {
        id: "lc-167-case-3",
        input: "numbers = [-1,0], target = -1",
        expected: "[1,2]",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-191",
    source: "leetcode",
    number: 191,
    title: "Number of 1 Bits",
    slug: "number-of-1-bits",
    difficulty: "Easy",
    topics: ["Divide and Conquer", "Bit Manipulation"],
    descriptionMarkdown:
      "# 191. Number of 1 Bits\n\nGiven a positive integer n, write a function that returns the number of set bits in its binary representation (also known as the Hamming weight).\nExample 1:\nExample 2:\nExample 3:\nConstraints:\n\n## Constraints\n\n- 1 <= n <= 231 - 1",
    notesMarkdown: "",
    functionName: "hammingWeight",
    judgeMode: "exact",
    code: "/**\n * @param {number} n\n * @return {number}\n */\nvar hammingWeight = function(n) {\n    \n};",
    testCases: [
      {
        id: "lc-191-case-1",
        input: "n = 11",
        expected: "3",
      },
      {
        id: "lc-191-case-2",
        input: "n = 128",
        expected: "1",
      },
      {
        id: "lc-191-case-3",
        input: "n = 2147483645",
        expected: "30",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-198",
    source: "leetcode",
    number: 198,
    title: "House Robber",
    slug: "house-robber",
    difficulty: "Medium",
    topics: ["Array", "Dynamic Programming"],
    descriptionMarkdown:
      "# 198. House Robber\n\nYou are a professional robber planning to rob houses along a street. Each house has a certain amount of money stashed, the only constraint stopping you from robbing each of them is that adjacent houses have security systems connected and it will automatically contact the police if two adjacent houses were broken into on the same night.\nGiven an integer array nums representing the amount of money of each house, return the maximum amount of money you can rob tonight without alerting the police.\nExample 1:\nExample 2:\nConstraints:\n\n## Constraints\n\n- 1 <= nums.length <= 100\n- 0 <= nums[i] <= 400",
    notesMarkdown: "",
    functionName: "rob",
    judgeMode: "exact",
    code: "/**\n * @param {number[]} nums\n * @return {number}\n */\nvar rob = function(nums) {\n    \n};",
    testCases: [
      {
        id: "lc-198-case-1",
        input: "nums = [1,2,3,1]",
        expected: "4",
      },
      {
        id: "lc-198-case-2",
        input: "nums = [2,7,9,3,1]",
        expected: "12",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-200",
    source: "leetcode",
    number: 200,
    title: "Number of Islands",
    slug: "number-of-islands",
    difficulty: "Medium",
    topics: ["Array", "Depth-First Search", "Breadth-First Search", "Union Find", "Matrix"],
    descriptionMarkdown:
      "# 200. Number of Islands\n\nGiven an m x n 2D binary grid grid which represents a map of '1's (land) and '0's (water), return the number of islands.\nAn island is surrounded by water and is formed by connecting adjacent lands horizontally or vertically. You may assume all four edges of the grid are all surrounded by water.\nExample 1:\nExample 2:\nConstraints:\n\n## Constraints\n\n- m == grid.length\n- n == grid[i].length\n- 1 <= m, n <= 300\n- grid[i][j] is '0' or '1'.",
    notesMarkdown: "",
    functionName: "numIslands",
    judgeMode: "exact",
    code: "/**\n * @param {character[][]} grid\n * @return {number}\n */\nvar numIslands = function(grid) {\n    \n};",
    testCases: [
      {
        id: "lc-200-case-1",
        input:
          'grid = [\n  ["1","1","1","1","0"],\n  ["1","1","0","1","0"],\n  ["1","1","0","0","0"],\n  ["0","0","0","0","0"]\n]',
        expected: "1",
      },
      {
        id: "lc-200-case-2",
        input:
          'grid = [\n  ["1","1","0","0","0"],\n  ["1","1","0","0","0"],\n  ["0","0","1","0","0"],\n  ["0","0","0","1","1"]\n]',
        expected: "3",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-202",
    source: "leetcode",
    number: 202,
    title: "Happy Number",
    slug: "happy-number",
    difficulty: "Easy",
    topics: ["Hash Table", "Math", "Two Pointers"],
    descriptionMarkdown:
      "# 202. Happy Number\n\nWrite an algorithm to determine if a number n is happy.\nA happy number is a number defined by the following process:\nReturn true if n is a happy number, and false if not.\nExample 1:\nExample 2:\nConstraints:\n\n## Constraints\n\n- 1 <= n <= 231 - 1",
    notesMarkdown: "",
    functionName: "isHappy",
    judgeMode: "exact",
    code: "/**\n * @param {number} n\n * @return {boolean}\n */\nvar isHappy = function(n) {\n    \n};",
    testCases: [
      {
        id: "lc-202-case-1",
        input: "n = 19",
        expected: "true",
      },
      {
        id: "lc-202-case-2",
        input: "n = 2",
        expected: "false",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-206",
    source: "leetcode",
    number: 206,
    title: "Reverse Linked List",
    slug: "reverse-linked-list",
    difficulty: "Easy",
    topics: ["Linked List", "Recursion"],
    descriptionMarkdown:
      "# 206. Reverse Linked List\n\nGiven the head of a singly linked list, reverse the list, and return the reversed list.\nExample 1:\nExample 2:\nExample 3:\nConstraints:\nFollow up: A linked list can be reversed either iteratively or recursively. Could you implement both?\n\n## Constraints\n\n- The number of nodes in the list is the range [0, 5000].\n- -5000 <= Node.val <= 5000",
    notesMarkdown: "",
    functionName: "reverseList",
    judgeMode: "exact",
    code: "/**\n * Definition for singly-linked list.\n * function ListNode(val, next) {\n *     this.val = (val===undefined ? 0 : val)\n *     this.next = (next===undefined ? null : next)\n * }\n */\n/**\n * @param {ListNode} head\n * @return {ListNode}\n */\nvar reverseList = function(head) {\n    \n};",
    testCases: [
      {
        id: "lc-206-case-1",
        input: "head = [1,2,3,4,5]",
        expected: "[5,4,3,2,1]",
      },
      {
        id: "lc-206-case-2",
        input: "head = [1,2]",
        expected: "[2,1]",
      },
      {
        id: "lc-206-case-3",
        input: "head = []",
        expected: "[]",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-210",
    source: "leetcode",
    number: 210,
    title: "Course Schedule II",
    slug: "course-schedule-ii",
    difficulty: "Medium",
    topics: ["Depth-First Search", "Breadth-First Search", "Graph", "Topological Sort"],
    descriptionMarkdown:
      '# 210. Course Schedule II\n\nThere are a total of numCourses courses you have to take, labeled from 0 to numCourses - 1. You are given an array prerequisites where prerequisites[i] = [ai, bi] indicates that you must take course bi first if you want to take course ai.\nReturn the ordering of courses you should take to finish all courses. If there are many valid answers, return any of them. If it is impossible to finish all courses, return an empty array.\nExample 1:\nExample 2:\nExample 3:\nConstraints:\n\n## Constraints\n\n- 1 <= numCourses <= 2000\n- 0 <= prerequisites.length <= numCourses * (numCourses - 1)\n- prerequisites[i].length == 2\n- 0 <= ai, bi < numCourses\n- ai != bi\n- All the pairs [ai, bi] are distinct.\n\n## Hints\n\n- This problem is equivalent to finding the topological order in a directed graph. If a cycle exists, no topological ordering exists and therefore it will be impossible to take all courses.\n- <a href="https://www.youtube.com/watch?v=ozso3xxkVGU" target="_blank">Topological Sort via DFS</a> - A great video tutorial (21 minutes) on Coursera explaining the basic concepts of Topological Sort.\n- Topological sort could also be done via <a href="http://en.wikipedia.org/wiki/Topological_sorting#Algorithms" target="_blank">BFS</a>.',
    notesMarkdown: "",
    functionName: "findOrder",
    judgeMode: "exact",
    code: "/**\n * @param {number} numCourses\n * @param {number[][]} prerequisites\n * @return {number[]}\n */\nvar findOrder = function(numCourses, prerequisites) {\n    \n};",
    testCases: [
      {
        id: "lc-210-case-1",
        input: "numCourses = 2, prerequisites = [[1,0]]",
        expected: "[0,1]",
      },
      {
        id: "lc-210-case-2",
        input: "numCourses = 4, prerequisites = [[1,0],[2,0],[3,1],[3,2]]",
        expected: "[0,2,1,3]",
      },
      {
        id: "lc-210-case-3",
        input: "numCourses = 1, prerequisites = []",
        expected: "[0]",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-215",
    source: "leetcode",
    number: 215,
    title: "Kth Largest Element in an Array",
    slug: "kth-largest-element-in-an-array",
    difficulty: "Medium",
    topics: ["Array", "Divide and Conquer", "Sorting", "Heap (Priority Queue)", "Quickselect"],
    descriptionMarkdown:
      "# 215. Kth Largest Element in an Array\n\nGiven an integer array nums and an integer k, return the kth largest element in the array.\nNote that it is the kth largest element in the sorted order, not the kth distinct element.\nCan you solve it without sorting?\nExample 1:\nExample 2:\nConstraints:\n\n## Constraints\n\n- 1 <= k <= nums.length <= 105\n- -104 <= nums[i] <= 104",
    notesMarkdown: "",
    functionName: "findKthLargest",
    judgeMode: "exact",
    code: "/**\n * @param {number[]} nums\n * @param {number} k\n * @return {number}\n */\nvar findKthLargest = function(nums, k) {\n    \n};",
    testCases: [
      {
        id: "lc-215-case-1",
        input: "nums = [3,2,1,5,6,4], k = 2",
        expected: "5",
      },
      {
        id: "lc-215-case-2",
        input: "nums = [3,2,3,1,2,4,5,5,6], k = 4",
        expected: "4",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-240",
    source: "leetcode",
    number: 240,
    title: "Search a 2D Matrix II",
    slug: "search-a-2d-matrix-ii",
    difficulty: "Medium",
    topics: ["Array", "Binary Search", "Divide and Conquer", "Matrix"],
    descriptionMarkdown:
      "# 240. Search a 2D Matrix II\n\nWrite an efficient algorithm that searches for a value target in an m x n integer matrix matrix. This matrix has the following properties:\nExample 1:\nExample 2:\nConstraints:\n\n## Constraints\n\n- m == matrix.length\n- n == matrix[i].length\n- 1 <= n, m <= 300\n- -109 <= matrix[i][j] <= 109\n- All the integers in each row are sorted in ascending order.\n- All the integers in each column are sorted in ascending order.\n- -109 <= target <= 109",
    notesMarkdown: "",
    functionName: "searchMatrix",
    judgeMode: "exact",
    code: "/**\n * @param {number[][]} matrix\n * @param {number} target\n * @return {boolean}\n */\nvar searchMatrix = function(matrix, target) {\n    \n};",
    testCases: [
      {
        id: "lc-240-case-1",
        input:
          "matrix = [[1,4,7,11,15],[2,5,8,12,19],[3,6,9,16,22],[10,13,14,17,24],[18,21,23,26,30]], target = 5",
        expected: "true",
      },
      {
        id: "lc-240-case-2",
        input:
          "matrix = [[1,4,7,11,15],[2,5,8,12,19],[3,6,9,16,22],[10,13,14,17,24],[18,21,23,26,30]], target = 20",
        expected: "false",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-268",
    source: "leetcode",
    number: 268,
    title: "Missing Number",
    slug: "missing-number",
    difficulty: "Easy",
    topics: ["Array", "Hash Table", "Math", "Binary Search", "Bit Manipulation", "Sorting"],
    descriptionMarkdown:
      "# 268. Missing Number\n\nGiven an array nums containing n distinct numbers in the range [0, n], return the only number in the range that is missing from the array.\nExample 1:\nExample 2:\nExample 3:\nConstraints:\nFollow up: Could you implement a solution using only O(1) extra space complexity and O(n) runtime complexity?\n\n## Constraints\n\n- n == nums.length\n- 1 <= n <= 104\n- 0 <= nums[i] <= n\n- All the numbers of nums are unique.",
    notesMarkdown: "",
    functionName: "missingNumber",
    judgeMode: "exact",
    code: "/**\n * @param {number[]} nums\n * @return {number}\n */\nvar missingNumber = function(nums) {\n    \n};",
    testCases: [
      {
        id: "lc-268-case-1",
        input: "nums = [3,0,1]",
        expected: "2",
      },
      {
        id: "lc-268-case-2",
        input: "nums = [0,1]",
        expected: "2",
      },
      {
        id: "lc-268-case-3",
        input: "nums = [9,6,4,2,3,5,7,0,1]",
        expected: "8",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-287",
    source: "leetcode",
    number: 287,
    title: "Find the Duplicate Number",
    slug: "find-the-duplicate-number",
    difficulty: "Medium",
    topics: ["Array", "Two Pointers", "Binary Search", "Bit Manipulation"],
    descriptionMarkdown:
      "# 287. Find the Duplicate Number\n\nGiven an array of integers nums containing n + 1 integers where each integer is in the range [1, n] inclusive.\nThere is only one repeated number in nums, return this repeated number.\nYou must solve the problem without modifying the array nums and using only constant extra space.\nExample 1:\nExample 2:\nExample 3:\nConstraints:\nFollow up:\n\n## Constraints\n\n- 1 <= n <= 105\n- nums.length == n + 1\n- 1 <= nums[i] <= n\n- All the integers in nums appear only once except for precisely one integer which appears two or more times.",
    notesMarkdown: "",
    functionName: "findDuplicate",
    judgeMode: "exact",
    code: "/**\n * @param {number[]} nums\n * @return {number}\n */\nvar findDuplicate = function(nums) {\n    \n};",
    testCases: [
      {
        id: "lc-287-case-1",
        input: "nums = [1,3,4,2,2]",
        expected: "2",
      },
      {
        id: "lc-287-case-2",
        input: "nums = [3,1,3,4,2]",
        expected: "3",
      },
      {
        id: "lc-287-case-3",
        input: "nums = [3,3,3,3,3]",
        expected: "3",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-300",
    source: "leetcode",
    number: 300,
    title: "Longest Increasing Subsequence",
    slug: "longest-increasing-subsequence",
    difficulty: "Medium",
    topics: ["Array", "Binary Search", "Dynamic Programming"],
    descriptionMarkdown:
      "# 300. Longest Increasing Subsequence\n\nGiven an integer array nums, return the length of the longest strictly increasing subsequence.\nExample 1:\nExample 2:\nExample 3:\nConstraints:\nFollow up: Can you come up with an algorithm that runs in O(n log(n)) time complexity?\n\n## Constraints\n\n- 1 <= nums.length <= 2500\n- -104 <= nums[i] <= 104",
    notesMarkdown: "",
    functionName: "lengthOfLIS",
    judgeMode: "exact",
    code: "/**\n * @param {number[]} nums\n * @return {number}\n */\nvar lengthOfLIS = function(nums) {\n    \n};",
    testCases: [
      {
        id: "lc-300-case-1",
        input: "nums = [10,9,2,5,3,7,101,18]",
        expected: "4",
      },
      {
        id: "lc-300-case-2",
        input: "nums = [0,1,0,3,2,3]",
        expected: "4",
      },
      {
        id: "lc-300-case-3",
        input: "nums = [7,7,7,7,7,7,7]",
        expected: "1",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-303",
    source: "leetcode",
    number: 303,
    title: "Range Sum Query - Immutable",
    slug: "range-sum-query-immutable",
    difficulty: "Easy",
    topics: ["Array", "Design", "Prefix Sum"],
    descriptionMarkdown:
      "# 303. Range Sum Query - Immutable\n\nGiven an integer array nums, handle multiple queries of the following type:\nImplement the NumArray class:\nExample 1:\nConstraints:\n\n## Constraints\n\n- 1 <= nums.length <= 104\n- -105 <= nums[i] <= 105\n- 0 <= left <= right < nums.length\n- At most 104 calls will be made to sumRange.",
    notesMarkdown: "",
    functionName: "NumArray",
    judgeMode: "exact",
    code: "/**\n * @param {number[]} nums\n */\nvar NumArray = function(nums) {\n    \n};\n\n/** \n * @param {number} left \n * @param {number} right\n * @return {number}\n */\nNumArray.prototype.sumRange = function(left, right) {\n    \n};\n\n/** \n * Your NumArray object will be instantiated and called as such:\n * var obj = new NumArray(nums)\n * var param_1 = obj.sumRange(left,right)\n */",
    testCases: [
      {
        id: "lc-303-case-1",
        input: "",
        expected: "undefined",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-322",
    source: "leetcode",
    number: 322,
    title: "Coin Change",
    slug: "coin-change",
    difficulty: "Medium",
    topics: ["Array", "Dynamic Programming", "Breadth-First Search"],
    descriptionMarkdown:
      "# 322. Coin Change\n\nYou are given an integer array coins representing coins of different denominations and an integer amount representing a total amount of money.\nReturn the fewest number of coins that you need to make up that amount. If that amount of money cannot be made up by any combination of the coins, return -1.\nYou may assume that you have an infinite number of each kind of coin.\nExample 1:\nExample 2:\nExample 3:\nConstraints:\n\n## Constraints\n\n- 1 <= coins.length <= 12\n- 1 <= coins[i] <= 231 - 1\n- 0 <= amount <= 104",
    notesMarkdown: "",
    functionName: "coinChange",
    judgeMode: "exact",
    code: "/**\n * @param {number[]} coins\n * @param {number} amount\n * @return {number}\n */\nvar coinChange = function(coins, amount) {\n    \n};",
    testCases: [
      {
        id: "lc-322-case-1",
        input: "coins = [1,2,5], amount = 11",
        expected: "3",
      },
      {
        id: "lc-322-case-2",
        input: "coins = [2], amount = 3",
        expected: "-1",
      },
      {
        id: "lc-322-case-3",
        input: "coins = [1], amount = 0",
        expected: "0",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-338",
    source: "leetcode",
    number: 338,
    title: "Counting Bits",
    slug: "counting-bits",
    difficulty: "Easy",
    topics: ["Dynamic Programming", "Bit Manipulation"],
    descriptionMarkdown:
      "# 338. Counting Bits\n\nGiven an integer n, return an array ans of length n + 1 such that for each i (0 <= i <= n), ans[i] is the number of 1's in the binary representation of i.\nExample 1:\nExample 2:\nConstraints:\nFollow up:\n\n## Constraints\n\n- 0 <= n <= 105\n\n## Hints\n\n- You should make use of what you have produced already.\n- Divide the numbers in ranges like [2-3], [4-7], [8-15] and so on. And try to generate new range from previous.\n- Or does the odd/even status of the number help you in calculating the number of 1s?",
    notesMarkdown: "",
    functionName: "countBits",
    judgeMode: "exact",
    code: "/**\n * @param {number} n\n * @return {number[]}\n */\nvar countBits = function(n) {\n    \n};",
    testCases: [
      {
        id: "lc-338-case-1",
        input: "n = 2",
        expected: "[0,1,1]",
      },
      {
        id: "lc-338-case-2",
        input: "n = 5",
        expected: "[0,1,1,2,1,2]",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-347",
    source: "leetcode",
    number: 347,
    title: "Top K Frequent Elements",
    slug: "top-k-frequent-elements",
    difficulty: "Medium",
    topics: [
      "Array",
      "Hash Table",
      "Divide and Conquer",
      "Sorting",
      "Heap (Priority Queue)",
      "Bucket Sort",
      "Counting",
      "Quickselect",
    ],
    descriptionMarkdown:
      "# 347. Top K Frequent Elements\n\nGiven an integer array nums and an integer k, return the k most frequent elements. You may return the answer in any order.\nExample 1:\nExample 2:\nConstraints:\nFollow up: Your algorithm's time complexity must be better than O(n log n), where n is the array's size.\n\n## Constraints\n\n- 1 <= nums.length <= 105\n- -104 <= nums[i] <= 104\n- k is in the range [1, the number of unique elements in the array].\n- It is guaranteed that the answer is unique.",
    notesMarkdown: "",
    functionName: "topKFrequent",
    judgeMode: "unordered-array",
    code: "/**\n * @param {number[]} nums\n * @param {number} k\n * @return {number[]}\n */\nvar topKFrequent = function(nums, k) {\n    \n};",
    testCases: [
      {
        id: "lc-347-case-1",
        input: "nums = [1,1,1,2,2,3], k = 2",
        expected: "[1,2]",
      },
      {
        id: "lc-347-case-2",
        input: "nums = [1], k = 1",
        expected: "[1]",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-373",
    source: "leetcode",
    number: 373,
    title: "Find K Pairs with Smallest Sums",
    slug: "find-k-pairs-with-smallest-sums",
    difficulty: "Medium",
    topics: ["Array", "Heap (Priority Queue)"],
    descriptionMarkdown:
      "# 373. Find K Pairs with Smallest Sums\n\nYou are given two integer arrays nums1 and nums2 sorted in non-decreasing order and an integer k.\nDefine a pair (u, v) which consists of one element from the first array and one element from the second array.\nReturn the k pairs (u1, v1), (u2, v2), ..., (uk, vk) with the smallest sums.\nExample 1:\nExample 2:\nConstraints:\n\n## Constraints\n\n- 1 <= nums1.length, nums2.length <= 105\n- -109 <= nums1[i], nums2[i] <= 109\n- nums1 and nums2 both are sorted in non-decreasing order.\n- 1 <= k <= 104\n- k <= nums1.length * nums2.length",
    notesMarkdown: "",
    functionName: "kSmallestPairs",
    judgeMode: "exact",
    code: "/**\n * @param {number[]} nums1\n * @param {number[]} nums2\n * @param {number} k\n * @return {number[][]}\n */\nvar kSmallestPairs = function(nums1, nums2, k) {\n    \n};",
    testCases: [
      {
        id: "lc-373-case-1",
        input: "nums1 = [1,7,11], nums2 = [2,4,6], k = 3",
        expected: "[[1,2],[1,4],[1,6]]",
      },
      {
        id: "lc-373-case-2",
        input: "nums1 = [1,1,2], nums2 = [1,2,3], k = 2",
        expected: "[[1,1],[1,1]]",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-416",
    source: "leetcode",
    number: 416,
    title: "Partition Equal Subset Sum",
    slug: "partition-equal-subset-sum",
    difficulty: "Medium",
    topics: ["Array", "Dynamic Programming"],
    descriptionMarkdown:
      "# 416. Partition Equal Subset Sum\n\nGiven an integer array nums, return true if you can partition the array into two subsets such that the sum of the elements in both subsets is equal or false otherwise.\nExample 1:\nExample 2:\nConstraints:\n\n## Constraints\n\n- 1 <= nums.length <= 200\n- 1 <= nums[i] <= 100",
    notesMarkdown: "",
    functionName: "canPartition",
    judgeMode: "exact",
    code: "/**\n * @param {number[]} nums\n * @return {boolean}\n */\nvar canPartition = function(nums) {\n    \n};",
    testCases: [
      {
        id: "lc-416-case-1",
        input: "nums = [1,5,11,5]",
        expected: "true",
      },
      {
        id: "lc-416-case-2",
        input: "nums = [1,2,3,5]",
        expected: "false",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-424",
    source: "leetcode",
    number: 424,
    title: "Longest Repeating Character Replacement",
    slug: "longest-repeating-character-replacement",
    difficulty: "Medium",
    topics: ["Hash Table", "String", "Sliding Window"],
    descriptionMarkdown:
      "# 424. Longest Repeating Character Replacement\n\nYou are given a string s and an integer k. You can choose any character of the string and change it to any other uppercase English character. You can perform this operation at most k times.\nReturn the length of the longest substring containing the same letter you can get after performing the above operations.\nExample 1:\nExample 2:\nConstraints:\n\n## Constraints\n\n- 1 <= s.length <= 105\n- s consists of only uppercase English letters.\n- 0 <= k <= s.length",
    notesMarkdown: "",
    functionName: "characterReplacement",
    judgeMode: "exact",
    code: "/**\n * @param {string} s\n * @param {number} k\n * @return {number}\n */\nvar characterReplacement = function(s, k) {\n    \n};",
    testCases: [
      {
        id: "lc-424-case-1",
        input: 's = "ABAB", k = 2',
        expected: "4",
      },
      {
        id: "lc-424-case-2",
        input: 's = "AABABBA", k = 1',
        expected: "4",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-435",
    source: "leetcode",
    number: 435,
    title: "Non-overlapping Intervals",
    slug: "non-overlapping-intervals",
    difficulty: "Medium",
    topics: ["Array", "Dynamic Programming", "Greedy", "Sorting"],
    descriptionMarkdown:
      "# 435. Non-overlapping Intervals\n\nGiven an array of intervals intervals where intervals[i] = [starti, endi], return the minimum number of intervals you need to remove to make the rest of the intervals non-overlapping.\nNote that intervals which only touch at a point are non-overlapping. For example, [1, 2] and [2, 3] are non-overlapping.\nExample 1:\nExample 2:\nExample 3:\nConstraints:\n\n## Constraints\n\n- 1 <= intervals.length <= 105\n- intervals[i].length == 2\n- -5 * 104 <= starti < endi <= 5 * 104",
    notesMarkdown: "",
    functionName: "eraseOverlapIntervals",
    judgeMode: "exact",
    code: "/**\n * @param {number[][]} intervals\n * @return {number}\n */\nvar eraseOverlapIntervals = function(intervals) {\n    \n};",
    testCases: [
      {
        id: "lc-435-case-1",
        input: "intervals = [[1,2],[2,3],[3,4],[1,3]]",
        expected: "1",
      },
      {
        id: "lc-435-case-2",
        input: "intervals = [[1,2],[1,2],[1,2]]",
        expected: "2",
      },
      {
        id: "lc-435-case-3",
        input: "intervals = [[1,2],[2,3]]",
        expected: "0",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-496",
    source: "leetcode",
    number: 496,
    title: "Next Greater Element I",
    slug: "next-greater-element-i",
    difficulty: "Easy",
    topics: ["Array", "Hash Table", "Stack", "Monotonic Stack"],
    descriptionMarkdown:
      "# 496. Next Greater Element I\n\nThe next greater element of some element x in an array is the first greater element that is to the right of x in the same array.\nYou are given two distinct 0-indexed integer arrays nums1 and nums2, where nums1 is a subset of nums2.\nFor each 0 <= i < nums1.length, find the index j such that nums1[i] == nums2[j] and determine the next greater element of nums2[j] in nums2. If there is no next greater element, then the answer for this query is -1.\nReturn an array ans of length nums1.length such that ans[i] is the next greater element as described above.\nExample 1:\nExample 2:\nConstraints:\n\n## Constraints\n\n- 1 <= nums1.length <= nums2.length <= 1000\n- 0 <= nums1[i], nums2[i] <= 104\n- All integers in nums1 and nums2 are unique.\n- All the integers of nums1 also appear in nums2.",
    notesMarkdown: "",
    functionName: "nextGreaterElement",
    judgeMode: "exact",
    code: "/**\n * @param {number[]} nums1\n * @param {number[]} nums2\n * @return {number[]}\n */\nvar nextGreaterElement = function(nums1, nums2) {\n    \n};",
    testCases: [
      {
        id: "lc-496-case-1",
        input: "nums1 = [4,1,2], nums2 = [1,3,4,2]",
        expected: "[-1,3,-1]",
      },
      {
        id: "lc-496-case-2",
        input: "nums1 = [2,4], nums2 = [1,2,3,4]",
        expected: "[3,-1]",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-503",
    source: "leetcode",
    number: 503,
    title: "Next Greater Element II",
    slug: "next-greater-element-ii",
    difficulty: "Medium",
    topics: ["Array", "Stack", "Monotonic Stack"],
    descriptionMarkdown:
      "# 503. Next Greater Element II\n\nGiven a circular integer array nums (i.e., the next element of nums[nums.length - 1] is nums[0]), return the next greater number for every element in nums.\nThe next greater number of a number x is the first greater number to its traversing-order next in the array, which means you could search circularly to find its next greater number. If it doesn't exist, return -1 for this number.\nExample 1:\nExample 2:\nConstraints:\n\n## Constraints\n\n- 1 <= nums.length <= 104\n- -109 <= nums[i] <= 109",
    notesMarkdown: "",
    functionName: "nextGreaterElements",
    judgeMode: "exact",
    code: "/**\n * @param {number[]} nums\n * @return {number[]}\n */\nvar nextGreaterElements = function(nums) {\n    \n};",
    testCases: [
      {
        id: "lc-503-case-1",
        input: "nums = [1,2,1]",
        expected: "[2,-1,2]",
      },
      {
        id: "lc-503-case-2",
        input: "nums = [1,2,3,4,3]",
        expected: "[2,3,4,-1,4]",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-523",
    source: "leetcode",
    number: 523,
    title: "Continuous Subarray Sum",
    slug: "continuous-subarray-sum",
    difficulty: "Medium",
    topics: ["Array", "Hash Table", "Math", "Prefix Sum"],
    descriptionMarkdown:
      "# 523. Continuous Subarray Sum\n\nGiven an integer array nums and an integer k, return true if nums has a good subarray or false otherwise.\nA good subarray is a subarray where:\nNote that:\nExample 1:\nExample 2:\nExample 3:\nConstraints:\n\n## Constraints\n\n- 1 <= nums.length <= 105\n- 0 <= nums[i] <= 109\n- 0 <= sum(nums[i]) <= 231 - 1\n- 1 <= k <= 231 - 1",
    notesMarkdown: "",
    functionName: "checkSubarraySum",
    judgeMode: "exact",
    code: "/**\n * @param {number[]} nums\n * @param {number} k\n * @return {boolean}\n */\nvar checkSubarraySum = function(nums, k) {\n    \n};",
    testCases: [
      {
        id: "lc-523-case-1",
        input: "nums = [23,2,4,6,7], k = 6",
        expected: "true",
      },
      {
        id: "lc-523-case-2",
        input: "nums = [23,2,6,4,7], k = 6",
        expected: "true",
      },
      {
        id: "lc-523-case-3",
        input: "nums = [23,2,6,4,7], k = 13",
        expected: "false",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-560",
    source: "leetcode",
    number: 560,
    title: "Subarray Sum Equals K",
    slug: "subarray-sum-equals-k",
    difficulty: "Medium",
    topics: ["Array", "Hash Table", "Prefix Sum"],
    descriptionMarkdown:
      "# 560. Subarray Sum Equals K\n\nGiven an array of integers nums and an integer k, return the total number of subarrays whose sum equals to k.\nA subarray is a contiguous non-empty sequence of elements within an array.\nExample 1:\nExample 2:\nConstraints:\n\n## Constraints\n\n- 1 <= nums.length <= 2 * 104\n- -1000 <= nums[i] <= 1000\n- -107 <= k <= 107\n\n## Hints\n\n- Will Brute force work here? Try to optimize it.\n- Can we optimize it by using some extra space?\n- What about storing sum frequencies in a hash table? Will it be useful?\n- sum(i,j)=sum(0,j)-sum(0,i), where sum(i,j) represents the sum of all the elements from index i to j-1.\r\n\r\nCan we use this property to optimize it.",
    notesMarkdown: "",
    functionName: "subarraySum",
    judgeMode: "exact",
    code: "/**\n * @param {number[]} nums\n * @param {number} k\n * @return {number}\n */\nvar subarraySum = function(nums, k) {\n    \n};",
    testCases: [
      {
        id: "lc-560-case-1",
        input: "nums = [1,1,1], k = 2",
        expected: "2",
      },
      {
        id: "lc-560-case-2",
        input: "nums = [1,2,3], k = 3",
        expected: "2",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-643",
    source: "leetcode",
    number: 643,
    title: "Maximum Average Subarray I",
    slug: "maximum-average-subarray-i",
    difficulty: "Easy",
    topics: ["Array", "Sliding Window"],
    descriptionMarkdown:
      "# 643. Maximum Average Subarray I\n\nYou are given an integer array nums consisting of n elements, and an integer k.\nFind a contiguous subarray whose length is equal to k that has the maximum average value and return this value. Any answer with a calculation error less than 10-5 will be accepted.\nExample 1:\nExample 2:\nConstraints:\n\n## Constraints\n\n- n == nums.length\n- 1 <= k <= n <= 105\n- -104 <= nums[i] <= 104",
    notesMarkdown: "",
    functionName: "findMaxAverage",
    judgeMode: "exact",
    code: "/**\n * @param {number[]} nums\n * @param {number} k\n * @return {number}\n */\nvar findMaxAverage = function(nums, k) {\n    \n};",
    testCases: [
      {
        id: "lc-643-case-1",
        input: "nums = [1,12,-5,-6,50,3], k = 4",
        expected: "12.75000",
      },
      {
        id: "lc-643-case-2",
        input: "nums = [5], k = 1",
        expected: "5.00000",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-733",
    source: "leetcode",
    number: 733,
    title: "Flood Fill",
    slug: "flood-fill",
    difficulty: "Easy",
    topics: ["Array", "Depth-First Search", "Breadth-First Search", "Matrix"],
    descriptionMarkdown:
      "# 733. Flood Fill\n\nYou are given an image represented by an m x n grid of integers image, where image[i][j] represents the pixel value of the image. You are also given three integers sr, sc, and color. Your task is to perform a flood fill on the image starting from the pixel image[sr][sc].\nTo perform a flood fill:\nReturn the modified image after performing the flood fill.\nExample 1:\nExample 2:\nConstraints:\n\n## Constraints\n\n- m == image.length\n- n == image[i].length\n- 1 <= m, n <= 50\n- 0 <= image[i][j], color < 216\n- 0 <= sr < m\n- 0 <= sc < n\n\n## Hints\n\n- Write a recursive function that paints the pixel if it's the correct color, then recurses on neighboring pixels.",
    notesMarkdown: "",
    functionName: "floodFill",
    judgeMode: "exact",
    code: "/**\n * @param {number[][]} image\n * @param {number} sr\n * @param {number} sc\n * @param {number} color\n * @return {number[][]}\n */\nvar floodFill = function(image, sr, sc, color) {\n    \n};",
    testCases: [
      {
        id: "lc-733-case-1",
        input: "image = [[1,1,1],[1,1,0],[1,0,1]], sr = 1, sc = 1, color = 2",
        expected: "[[2,2,2],[2,2,0],[2,0,1]]",
      },
      {
        id: "lc-733-case-2",
        input: "image = [[0,0,0],[0,0,0]], sr = 0, sc = 0, color = 0",
        expected: "[[0,0,0],[0,0,0]]",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-739",
    source: "leetcode",
    number: 739,
    title: "Daily Temperatures",
    slug: "daily-temperatures",
    difficulty: "Medium",
    topics: ["Array", "Stack", "Monotonic Stack"],
    descriptionMarkdown:
      "# 739. Daily Temperatures\n\nGiven an array of integers temperatures represents the daily temperatures, return an array answer such that answer[i] is the number of days you have to wait after the ith day to get a warmer temperature. If there is no future day for which this is possible, keep answer[i] == 0 instead.\nExample 1:\nExample 2:\nExample 3:\nConstraints:\n\n## Constraints\n\n- 1 <= temperatures.length <= 105\n- 30 <= temperatures[i] <= 100\n\n## Hints\n\n- If the temperature is say, 70 today, then in the future a warmer temperature must be either 71, 72, 73, ..., 99, or 100.  We could remember when all of them occur next.",
    notesMarkdown: "",
    functionName: "dailyTemperatures",
    judgeMode: "exact",
    code: "/**\n * @param {number[]} temperatures\n * @return {number[]}\n */\nvar dailyTemperatures = function(temperatures) {\n    \n};",
    testCases: [
      {
        id: "lc-739-case-1",
        input: "temperatures = [73,74,75,71,69,72,76,73]",
        expected: "[1,1,4,2,1,1,0,0]",
      },
      {
        id: "lc-739-case-2",
        input: "temperatures = [30,40,50,60]",
        expected: "[1,1,1,0]",
      },
      {
        id: "lc-739-case-3",
        input: "temperatures = [30,60,90]",
        expected: "[1,1,0]",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-994",
    source: "leetcode",
    number: 994,
    title: "Rotting Oranges",
    slug: "rotting-oranges",
    difficulty: "Medium",
    topics: ["Array", "Breadth-First Search", "Matrix"],
    descriptionMarkdown:
      "# 994. Rotting Oranges\n\nYou are given an m x n grid where each cell can have one of three values:\nEvery minute, any fresh orange that is 4-directionally adjacent to a rotten orange becomes rotten.\nReturn the minimum number of minutes that must elapse until no cell has a fresh orange. If this is impossible, return -1.\nExample 1:\nExample 2:\nExample 3:\nConstraints:\n\n## Constraints\n\n- m == grid.length\n- n == grid[i].length\n- 1 <= m, n <= 10\n- grid[i][j] is 0, 1, or 2.",
    notesMarkdown: "",
    functionName: "orangesRotting",
    judgeMode: "exact",
    code: "/**\n * @param {number[][]} grid\n * @return {number}\n */\nvar orangesRotting = function(grid) {\n    \n};",
    testCases: [
      {
        id: "lc-994-case-1",
        input: "grid = [[2,1,1],[1,1,0],[0,1,1]]",
        expected: "4",
      },
      {
        id: "lc-994-case-2",
        input: "grid = [[2,1,1],[0,1,1],[1,0,1]]",
        expected: "-1",
      },
      {
        id: "lc-994-case-3",
        input: "grid = [[0,2]]",
        expected: "0",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-1143",
    source: "leetcode",
    number: 1143,
    title: "Longest Common Subsequence",
    slug: "longest-common-subsequence",
    difficulty: "Medium",
    topics: ["String", "Dynamic Programming"],
    descriptionMarkdown:
      "# 1143. Longest Common Subsequence\n\nGiven two strings text1 and text2, return the length of their longest common subsequence. If there is no common subsequence, return 0.\nA subsequence of a string is a new string generated from the original string with some characters (can be none) deleted without changing the relative order of the remaining characters.\nA common subsequence of two strings is a subsequence that is common to both strings.\nExample 1:\nExample 2:\nExample 3:\nConstraints:\n\n## Constraints\n\n- 1 <= text1.length, text2.length <= 1000\n- text1 and text2 consist of only lowercase English characters.\n\n## Hints\n\n- Try dynamic programming. \r\nDP[i][j] represents the longest common subsequence of text1[0 ... i] & text2[0 ... j].\n- DP[i][j] = DP[i - 1][j - 1] + 1 , if text1[i] == text2[j]\r\nDP[i][j] = max(DP[i - 1][j], DP[i][j - 1]) , otherwise",
    notesMarkdown: "",
    functionName: "longestCommonSubsequence",
    judgeMode: "exact",
    code: "/**\n * @param {string} text1\n * @param {string} text2\n * @return {number}\n */\nvar longestCommonSubsequence = function(text1, text2) {\n    \n};",
    testCases: [
      {
        id: "lc-1143-case-1",
        input: 'text1 = "abcde", text2 = "ace"',
        expected: "3",
      },
      {
        id: "lc-1143-case-2",
        input: 'text1 = "abc", text2 = "abc"',
        expected: "3",
      },
      {
        id: "lc-1143-case-3",
        input: 'text1 = "abc", text2 = "def"',
        expected: "0",
      },
    ],
    submissions: [],
  },
  {
    id: "lc-1834",
    source: "leetcode",
    number: 1834,
    title: "Single-Threaded CPU",
    slug: "single-threaded-cpu",
    difficulty: "Medium",
    topics: ["Array", "Sorting", "Heap (Priority Queue)"],
    descriptionMarkdown:
      "# 1834. Single-Threaded CPU\n\nYou are given n​​​​​​ tasks labeled from 0 to n - 1 represented by a 2D integer array tasks, where tasks[i] = [enqueueTimei, processingTimei] means that the i​​​​​​th​​​​ task will be available to process at enqueueTimei and will take processingTimei to finish processing.\nYou have a single-threaded CPU that can process at most one task at a time and will act in the following way:\nReturn the order in which the CPU will process the tasks.\nExample 1:\nExample 2:\nConstraints:\n\n## Constraints\n\n- tasks.length == n\n- 1 <= n <= 105\n- 1 <= enqueueTimei, processingTimei <= 109\n\n## Hints\n\n- To simulate the problem we first need to note that if at any point in time there are no enqueued tasks we need to wait to the smallest enqueue time of a non-processed element\n- We need a data structure like a min-heap to support choosing the task with the smallest processing time from all the enqueued tasks",
    notesMarkdown: "",
    functionName: "getOrder",
    judgeMode: "exact",
    code: "/**\n * @param {number[][]} tasks\n * @return {number[]}\n */\nvar getOrder = function(tasks) {\n    \n};",
    testCases: [
      {
        id: "lc-1834-case-1",
        input: "tasks = [[1,2],[2,4],[3,2],[4,1]]",
        expected: "[0,2,3,1]",
      },
      {
        id: "lc-1834-case-2",
        input: "tasks = [[7,10],[7,12],[7,5],[7,4],[7,2]]",
        expected: "[4,3,2,0,1]",
      },
    ],
    submissions: [],
  },
];
